version: '3.8'

services:
  flask_server:
    build:
      context: .
    ports:
      - 5000:5000
    env_file:
      - database.conf
    volumes:
      - ./:/src
    depends_on:
      - postgres_db
    networks:
      - db_network

  postgres_db:
    image: postgres
    ports:
     - 5432:5432
    env_file:
      - database.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
